# This is a basic workflow to help you get started with Actions

name: GITHUBACTIONS_WORKFLOW

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs: 
        id:
          description: 'id identifier'
          required: false
        param2:
          description: 'param1 identifier'
          required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # build
      - name: BUILD
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
 	run: echo "Hello, world!"

      # deploy	
      - name: DEPLOY
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
 	run: echo "Hello, world!"

      # test
      - name: TEST
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
 	run: echo "Hello, world!"


      # other actions
      - name: OTHER_ACTIONS
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
 	run: echo "Hello, world!"


    # outputs
    outputs:
      output1: "Test output1"
      output2: "Test output2"
      
